-- This was generated by ChatGPT
module AoC.Framework where

-- A típusok nincsenek fixálva, 'c' és 'd' tetszőleges típus lehet!
type Parser c d = c -> IO d
type Solver c d = c -> d -> Int

-- A programMatrix sorának generikus sablonja
data Task c d = Task
    { config  :: c
    , message :: String
    , parser  :: Parser c d
    , solver  :: Solver c d
    }

-- Ez a futtató motor, amit a libAoC ad a programozónak. 
-- Bármilyen 'c' és 'd' típussal működik!
runAoC :: [Task c d] -> IO ()
runAoC tasks = mapM_ runTask tasks
  where
    runTask task = do
        parsedData <- (parser task) (config task)
        let result = (solver task) (config task) parsedData
        putStrLn $ message task ++ show result

